version: '3.9'

services:
  backend:
    build: .
    container_name: assistance_backend
    command: >
      sh -c "python manage.py migrate &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: assistance
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  worker:
    build: .
    container_name: assistance_worker
    command: >
      celery -A config worker -l info --concurrency=10
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: assistance
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  db:
    image: postgres:16-alpine
    container_name: assistance_db
    environment:
      POSTGRES_DB: assistance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d assistance"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  redis:
    image: redis:7-alpine
    container_name: assistance_redis
    ports:
      - "6379:6379"
    restart: always
